### PR TITLE
Update Tika to 1.11

### PR DESCRIPTION
**Pull request by freein**
Rake did update the ripple.config automatically.

### CODE REVIEW

**Comment by KevM** [comment]
Just curious and I wish I had better automation in place. Did you run tests and everything passed?

**Comment by freein** [comment]
I followed the instructions in the readme. Exectued rake after the update. No errors.

I also tried using the latest IKVM, but nearly every test failed so I reverted.

**Comment by KevM** [comment]
Thank you. I'll try to cut a Nuget tonight. Do you need that in a hurry?

**Comment by freein** [comment]
Thanks, but no stress.

**Comment by kylegalbraith** [comment]
Is there any update on cutting the fresh nuget? We would like to give this a spin in our application.

**Pull request merged**
